import { v4 as uuidv4 } from 'uuid';

export const db = {
  seasons: [
    {
      id: 'summer',
      name: 'Summer',
      months: 'December – February',
      color: '#EF9F27',
      description: 'Peak stone fruit and tomato season. Cool Bundanoon nights make BBQ smoke irresistible outdoors. Best season for alfresco canapés and overnight grazing.',
      marketingHook: 'Smoke from the highlands — slow-cooked Snake Creek lamb, stone fruit pavlova, and wines from vineyards you can see from the veranda. All sourced within 20km of your table.',
    },
    {
      id: 'autumn',
      name: 'Autumn',
      months: 'March – May',
      color: '#D85A30',
      description: 'The richest season for the Southern Highlands. Root vegetables, pumpkin, wild mushrooms, and game. Flemington delivers exceptional value on root vegetables and brassicas.',
      marketingHook: 'When the highlands turn amber — slow-smoked brisket, root vegetable feasts, and pear tarts made with fruit picked the morning of your arrival.',
    },
    {
      id: 'winter',
      name: 'Winter',
      months: 'June – August',
      color: '#378ADD',
      description: 'Bundanoon averages 0°C nights. Smoked meats reheated inside are the hero. The open wood fires in ballroom and dining room become major atmosphere assets.',
      marketingHook: 'Smokey Men Catering in winter: open fires, slow-smoked short ribs, and steamed citrus pudding at a candlelit table for 36. The coldest nights make the best dinners.',
    },
    {
      id: 'spring',
      name: 'Spring',
      months: 'September – November',
      color: '#639922',
      description: 'Most photogenic season — herb garden bursting, asparagus and peas at Flemington, early strawberries arriving. Perfect wedding and birthday dinner season.',
      marketingHook: 'New season Snake Creek lamb, asparagus from Flemington at dawn, strawberry pavlova made in a 140-year-old kitchen. The most beautiful time to gather at Smokey Men Catering.',
    },
  ],

  ingredients: [
    // SUMMER
    { id: uuidv4(), seasonId: 'summer', name: 'Zucchini', pricePerKg: 1.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Heirloom tomatoes', pricePerKg: 2.8, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Corn cobs', pricePerKg: 0.6, unit: 'each', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Eggplant', pricePerKg: 2.2, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Capsicum', pricePerKg: 3.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Peaches', pricePerKg: 2.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Cherries', pricePerKg: 8.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Snake Creek lamb shoulder', pricePerKg: 18.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'summer', name: "Potter's Pantry sourdough", pricePerKg: 8.0, unit: 'loaf', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'summer', name: 'Pork belly', pricePerKg: 12.0, unit: 'kg', type: 'standard', source: 'flemington' },
    { id: uuidv4(), seasonId: 'summer', name: 'Chicken thighs', pricePerKg: 7.0, unit: 'kg', type: 'standard', source: 'flemington' },
    // AUTUMN
    { id: uuidv4(), seasonId: 'autumn', name: 'Pumpkin', pricePerKg: 1.2, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Sweet potato', pricePerKg: 2.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Parsnip', pricePerKg: 2.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Wild mushrooms', pricePerKg: 6.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Apples', pricePerKg: 2.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Pears', pricePerKg: 2.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Leeks', pricePerKg: 2.8, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Beetroot', pricePerKg: 2.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Snake Creek beef brisket', pricePerKg: 20.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Southern Highlands pork shoulder', pricePerKg: 14.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Cauliflower', pricePerKg: 2.5, unit: 'head', type: 'standard', source: 'flemington' },
    { id: uuidv4(), seasonId: 'autumn', name: 'Kale', pricePerKg: 2.0, unit: 'bunch', type: 'standard', source: 'flemington' },
    // WINTER
    { id: uuidv4(), seasonId: 'winter', name: 'Cauliflower', pricePerKg: 1.5, unit: 'head', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Broccoli', pricePerKg: 1.8, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Savoy cabbage', pricePerKg: 1.2, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Carrots', pricePerKg: 1.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Onions', pricePerKg: 1.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Oranges', pricePerKg: 2.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Lemons', pricePerKg: 1.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Kale', pricePerKg: 1.8, unit: 'bunch', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'winter', name: 'Snake Creek beef short ribs', pricePerKg: 22.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'winter', name: 'Southern Highlands pork belly', pricePerKg: 12.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'winter', name: 'Bundanoon lamb', pricePerKg: 18.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'winter', name: 'Celery', pricePerKg: 1.5, unit: 'head', type: 'standard', source: 'flemington' },
    // SPRING
    { id: uuidv4(), seasonId: 'spring', name: 'Asparagus', pricePerKg: 4.0, unit: 'bunch', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Peas', pricePerKg: 3.5, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Broad beans', pricePerKg: 4.0, unit: 'kg', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Baby spinach', pricePerKg: 2.0, unit: 'bunch', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Spring onions', pricePerKg: 1.5, unit: 'bunch', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Strawberries', pricePerKg: 4.0, unit: 'punnet', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Fennel', pricePerKg: 2.5, unit: 'bulb', type: 'hero', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Snake Creek new season lamb', pricePerKg: 17.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'spring', name: 'Local free-range chicken', pricePerKg: 12.0, unit: 'kg', type: 'local', source: 'local' },
    { id: uuidv4(), seasonId: 'spring', name: 'Zucchini flowers', pricePerKg: 8.0, unit: 'dozen', type: 'standard', source: 'flemington' },
    { id: uuidv4(), seasonId: 'spring', name: 'Early stone fruit', pricePerKg: 4.0, unit: 'kg', type: 'standard', source: 'flemington' },
  ],

  menus: [
    // ── SUMMER ──────────────────────────────────────────────
    { id: uuidv4(), seasonId: 'summer', service: 'Friday Arrival', title: 'Summer Highlands Welcome Board', badge: 'Sutton Forest wines on arrival', badgeType: 'local', items: ['Charred capsicum + whipped ricotta crostini','Heirloom tomato bruschetta, garden basil','Smoked chicken, garden herb aioli skewers','Local charcuterie, Bundanoon deli cheese','Peach & prosciutto bites'] },
    { id: uuidv4(), seasonId: 'summer', service: 'Friday Dinner — Seated 36', title: 'Slow-smoked Lamb & Summer Vegetable Feast', badge: 'Smoked off-site, reheated on-site', badgeType: 'bbq', items: ['Smoked Snake Creek lamb shoulder (off-site smoker)','Pulled pork belly, apple slaw','Roasted corn salad, jalapeño, coriander','Charred zucchini, lemon, feta','Heirloom tomato salad, basil oil',"Potter's Pantry sourdough, house butter",'Cherry & peach pavlova'] },
    { id: uuidv4(), seasonId: 'summer', service: 'Saturday Breakfast', title: 'BBQ Country Station', badge: 'Zero waste — reuses dinner produce', badgeType: 'bbq', items: ['6-burner BBQ: bacon, eggs to order, snags','Grilled tomatoes (from dinner surplus)','Sourdough toast, local preserves','Fresh juice, filter coffee'] },
    { id: uuidv4(), seasonId: 'summer', service: 'Saturday Lunch', title: 'Smoky Pull-apart Picnic Hampers', badge: 'Excellent upsell for Morton NP hikers', badgeType: 'local', items: ['Leftover smoked meats, fresh rolls','Roasted vegetable + pesto wrap','Corn + capsicum slaw','Seasonal stone fruit',"Potter's Pantry sweet pastry"] },
    { id: uuidv4(), seasonId: 'summer', service: 'Saturday Dinner — Celebration', title: 'Three-course Highlands Feast', badge: 'Brisket smoked day-prior, reheated', badgeType: 'bbq', items: ['Entrée: Grilled peach & brie crostata, honey, thyme','Main: BBQ beef brisket, chimichurri, roasted eggplant','Sides: Charred corn, charred capsicum salad','Dessert: Pavlova, cherry compote, cream'] },
    { id: uuidv4(), seasonId: 'summer', service: 'Sunday Departure', title: 'Continental + Hot Egg Station', badge: null, badgeType: null, items: ['Yoghurt, granola, seasonal stone fruit',"Pastries from Potter's Pantry",'Scrambled egg hot station, BBQ'] },
    // ── AUTUMN ──────────────────────────────────────────────
    { id: uuidv4(), seasonId: 'autumn', service: 'Friday Arrival', title: 'Highlands Harvest Welcome Board', badge: 'Sutton Forest cool-climate pinot', badgeType: 'local', items: ['Warm spiced pumpkin hummus, crackers','Roasted beetroot, goat\'s curd, walnut crostini','Smoked pork rillettes, sourdough','Bundanoon deli board: local cheese, pickles, fig jam','Sliced pear & blue cheese bites'] },
    { id: uuidv4(), seasonId: 'autumn', service: 'Friday Dinner — Seated 36', title: 'Smoke & Root Feast', badge: 'Brisket & shoulder smoked off-site', badgeType: 'bbq', items: ['Smoked beef brisket, smoked pork shoulder','Apple & fennel coleslaw','Roasted root vegetable medley (pumpkin, parsnip, sweet potato)','Mushroom & leek gratin','Char-grilled kale, lemon',"Potter's Pantry sourdough, whipped butter",'Pear & ginger tart, cream'] },
    { id: uuidv4(), seasonId: 'autumn', service: 'Saturday Breakfast', title: 'Autumn Harvest BBQ Station', badge: 'Brisket hash — zero-waste hero dish', badgeType: 'bbq', items: ['Smoked brisket hash, fried egg (dinner leftovers)','Grilled mushrooms, wilted kale','Sourdough toast, local honey','Spiced apple juice (warm option)'] },
    { id: uuidv4(), seasonId: 'autumn', service: 'Saturday Lunch', title: 'Pumpkin Soup Station + Hampers', badge: 'Soup flask upsell for Morton NP hikers', badgeType: 'local', items: ['Roasted pumpkin & leek soup','Pulled pork & apple rolls','Beetroot & feta salad','Local seasonal fruit'] },
    { id: uuidv4(), seasonId: 'autumn', service: 'Saturday Dinner — Celebration', title: 'Three-course Root & Smoke', badge: 'Lamb smoked off-site, day-of reheat', badgeType: 'bbq', items: ['Entrée: Mushroom & brie tart, caramelised onion','Main: Smoked lamb shoulder, roasted root veg, jus','Dessert: Local honey panna cotta, poached pear'] },
    { id: uuidv4(), seasonId: 'autumn', service: 'Sunday Departure', title: 'Warm Continental Station', badge: null, badgeType: null, items: ['Granola, yoghurt, stewed apple & pear',"Potter's Pantry croissants, local jam",'Scrambled eggs, BBQ-smoked bacon'] },
    // ── WINTER ──────────────────────────────────────────────
    { id: uuidv4(), seasonId: 'winter', service: 'Friday Arrival', title: 'Fireside Welcome Board', badge: 'Served fireside in ballroom', badgeType: 'local', items: ['Smoked pork rillettes, sourdough, Dijon','Bundanoon deli board: aged cheddar, pickled walnuts, local honey','Warm cauliflower bites, harissa yoghurt','Citrus-cured salmon blinis','Warm spiced nuts (bar area)'] },
    { id: uuidv4(), seasonId: 'winter', service: 'Friday Dinner — Seated 36', title: 'Winter Smoke & Fire Feast', badge: 'Short ribs smoked off-site, reheated in jus', badgeType: 'bbq', items: ['Smoked beef short ribs, rich jus','Smoked pork belly, apple & cabbage braise','Roasted cauliflower, golden raisins, capers','Braised savoy cabbage, caraway butter','Roasted root vegetables, orange gremolata',"Potter's Pantry sourdough, bone marrow butter",'Steamed citrus pudding, orange custard'] },
    { id: uuidv4(), seasonId: 'winter', service: 'Saturday Breakfast', title: 'Winter Hearth Breakfast', badge: 'Indoor service — rib hash is the hero', badgeType: 'bbq', items: ['Short rib hash, fried egg, salsa verde','Grilled broccoli, chilli, lemon on toast','Thick-cut sourdough, cultured butter, local marmalade','Hot chocolate station + filter coffee'] },
    { id: uuidv4(), seasonId: 'winter', service: 'Saturday Lunch', title: 'Pot of Soup + Sourdough', badge: 'Broth from smoked pork off-cuts — zero waste', badgeType: 'local', items: ['Winter vegetable & smoked pork broth','Grilled sourdough, Bundanoon butter','Simple kale & carrot slaw',"Potter's Pantry apple cake"] },
    { id: uuidv4(), seasonId: 'winter', service: 'Saturday Dinner — Celebration', title: 'Three-course Winter Feast', badge: 'Best season for long smoked/braised meats', badgeType: 'bbq', items: ['Entrée: Slow-braised oxtail on grilled polenta, gremolata','Main: Smoked lamb shoulder, white bean cassoulet, kale','Dessert: Warm orange tart, crème fraîche'] },
    { id: uuidv4(), seasonId: 'winter', service: 'Sunday Departure', title: 'Warm Continental Station', badge: null, badgeType: null, items: ['Overnight porridge station, brown sugar, cream',"Potter's Pantry croissants, local citrus jam",'Fried egg station, toast'] },
    // ── SPRING ──────────────────────────────────────────────
    { id: uuidv4(), seasonId: 'spring', service: 'Friday Arrival', title: 'Spring Garden Welcome Board', badge: 'Most Instagrammable arrival board of the year', badgeType: 'local', items: ['Garden herb frittata bites, garden mint yoghurt','Smoked chicken & asparagus skewers','Zucchini flower fritters (when in season)','Bundanoon deli board, local feta, herb oil','Strawberry & brie crostini'] },
    { id: uuidv4(), seasonId: 'spring', service: 'Friday Dinner — Seated 36', title: 'New Season Lamb & Spring Table', badge: 'Lamb smoked off-site — best of year', badgeType: 'bbq', items: ['New season Snake Creek lamb shoulder (smoked off-site)','Smoked free-range chicken halves','Asparagus, broad bean & pea salad, mint','Fennel & orange slaw','Roasted spring vegetables, herb oil',"Potter's Pantry sourdough, spring herb butter",'Pavlova, strawberries, rosewater cream'] },
    { id: uuidv4(), seasonId: 'spring', service: 'Saturday Breakfast', title: 'Spring Garden BBQ Station', badge: null, badgeType: null, items: ['BBQ eggs, asparagus soldiers, garden herbs','Smoked chicken omelettes (from Friday dinner surplus)','Spring onion & feta fritters','Local strawberries, yoghurt, honey',"Potter's Pantry sourdough, fresh butter"] },
    { id: uuidv4(), seasonId: 'spring', service: 'Saturday Lunch', title: 'Garden Picnic Hampers', badge: 'Peak season for Morton NP hamper upsell', badgeType: 'local', items: ['Smoked chicken, asparagus & pea salad wrap','Fennel slaw, sourdough roll','Seasonal fruit, local strawberries',"Potter's Pantry honey cake"] },
    { id: uuidv4(), seasonId: 'spring', service: 'Saturday Dinner — Celebration', title: 'Three-course Spring Celebration', badge: 'Most photogenic dinner of the year', badgeType: 'local', items: ['Entrée: Asparagus, zucchini flower & ricotta tart','Main: Smoked lamb shoulder, spring pea purée, mint jus','Dessert: Strawberry pavlova, rosewater, edible garden flowers'] },
    { id: uuidv4(), seasonId: 'spring', service: 'Sunday Departure', title: 'Spring Continental Station', badge: null, badgeType: null, items: ['Granola, strawberry yoghurt, fresh garden mint',"Potter's Pantry seasonal pastries",'BBQ egg station, spring onion'] },
  ],

  costings: {
    packageA: {
      label: 'Package A — Full Weekend Residential (Fri–Sun), 36 pax',
      lines: [
        { label: 'Food cost', low: 2220, high: 2900, note: 'Flemington markets sourced morning of event' },
        { label: 'Staffing (2 chefs + 2–3 FOH)', low: 1200, high: 1600, note: '2 chefs + kitchen hand + FOH' },
        { label: 'Smoker hire + transport (20km)', low: 350, high: 500, note: 'Off-site pit, return run' },
        { label: 'Equipment + linen', low: 200, high: 300, note: 'Portable induction, bain-marie, linen' },
        { label: 'Total cost estimate', low: 3970, high: 5300, note: 'All-in before beverages' },
        { label: 'Recommended sell price', low: 7200, high: 8500, note: '$200–$236 pp' },
      ],
    },
    packageB: {
      label: 'Package B — Celebration Event (Birthday / Wedding), 36 pax',
      lines: [
        { label: 'Canapés + dinner food', low: 1400, high: 1800, note: 'Single event day' },
        { label: 'Staffing (2 chefs + 2 FOH)', low: 900, high: 1200, note: '2 chefs + 2 FOH' },
        { label: 'Smoker + transport', low: 350, high: 500, note: 'Off-site pit, return run' },
        { label: 'Equipment + linen', low: 150, high: 250, note: '' },
        { label: 'Total cost estimate', low: 2800, high: 3750, note: 'All-in before beverages' },
        { label: 'Recommended sell price', low: 5400, high: 6500, note: '$150–$180 pp' },
      ],
    },
    seasonalVariance: [
      { season: 'Summer', adj: 0, driver: 'Stone fruit premium; low brassica need', margin: 57 },
      { season: 'Autumn', adj: -200, driver: 'Cheapest root veg season; best mushroom value', margin: 60 },
      { season: 'Winter', adj: -300, driver: 'Brassicas at minimum; hearty proteins stretch further', margin: 61 },
      { season: 'Spring', adj: 100, driver: 'Asparagus + zucchini flowers premium; worth it for marketing', margin: 56 },
    ],
  },
};
